// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgWp4qwtIPRHi1TdLFK-U76UMC5FazBJI',
    appId: '1:567426905461:web:672ea8c9659ac398d80f3c',
    messagingSenderId: '567426905461',
    projectId: 'calendar-scheduler-fluorjo',
    authDomain: 'calendar-scheduler-fluorjo.firebaseapp.com',
    storageBucket: 'calendar-scheduler-fluorjo.appspot.com',
    measurementId: 'G-CPYS8KFTFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOkENIFrU5tCP78-HxmxdMEMtHiwz1MUU',
    appId: '1:567426905461:android:77070802b131a52dd80f3c',
    messagingSenderId: '567426905461',
    projectId: 'calendar-scheduler-fluorjo',
    storageBucket: 'calendar-scheduler-fluorjo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi7QYGiGhn_aCJQSGR1ll0wJ0Pnua23MU',
    appId: '1:567426905461:ios:8d0263e840c32a17d80f3c',
    messagingSenderId: '567426905461',
    projectId: 'calendar-scheduler-fluorjo',
    storageBucket: 'calendar-scheduler-fluorjo.appspot.com',
    iosClientId: '567426905461-ddod2eu0hcj9q1rgved1ffls8noesv03.apps.googleusercontent.com',
    iosBundleId: 'com.example.calendarScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi7QYGiGhn_aCJQSGR1ll0wJ0Pnua23MU',
    appId: '1:567426905461:ios:8d0263e840c32a17d80f3c',
    messagingSenderId: '567426905461',
    projectId: 'calendar-scheduler-fluorjo',
    storageBucket: 'calendar-scheduler-fluorjo.appspot.com',
    iosClientId: '567426905461-ddod2eu0hcj9q1rgved1ffls8noesv03.apps.googleusercontent.com',
    iosBundleId: 'com.example.calendarScheduler',
  );
}
